version: "2.2"

x-webs: &webs
  image: apache-php-webserver
  environment:
    DB_NAME: "${DBNAME}"
    DB_USER: "root"
    DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    DB_HOST: "mysqldb"
  volumes:
    - ./html:/var/www/html
  depends_on:
    mysqldb:
      condition: service_healthy

services:
  mysqldb:
      image: mysql:5.6.35
      environment:
        MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
        MYSQL_DATABASE: "${DBNAME}"
      healthcheck:
        test: ["CMD","mysqladmin", "ping", "-p${DB_ROOT_PASSWORD}"]
        timeout: 10s
        retries: 20
      volumes:
        - mysqlData:/var/lib/mysql
  web1:
      <<: *webs
  web2:
      <<: *webs
  proxy:
    image: nginx:1.21.3
    depends_on:
      - "web1"
      - "web2"
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"

volumes:
  mysqlData: {}
